#pragma once

#define OFXGGML_DIFFUSION_VERSION_MAJOR 1
#define OFXGGML_DIFFUSION_VERSION_MINOR 0
#define OFXGGML_DIFFUSION_VERSION_PATCH 1
#define OFXGGML_DIFFUSION_VERSION_STRING "1.0.1"

inline const char * ofxGgmlDiffusionGetVersionString() {
	return OFXGGML_DIFFUSION_VERSION_STRING;
}
